language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugin.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-drupal.gemspec
- gem install sensu-plugins-drupal-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: JUGCtwpwI0L/hspq2UORjPbsh0u8PmjPestIvRO9fsxBFX8TIqLQ0UoqS3wCeZENJm+qaNeIzOTeqm4tzYgKjthsWw9R8YioHSANCkJGUqjujA6awXmWyay+UP5PXdDEAqDppqrUucdE3gstDvPJgA2KXHjwbAeHjgfzZioSBUg=
  gem: sensu-plugins-drupal
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-drupal
